config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :interests
  end

  root 'topics#index'

  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'sessions#create'
  get    '/signin'                  => 'sessions#new',     as: :signin
  delete '/signout'                 => 'sessions#destroy', as: :signout
  get    '/auth/failure'            => 'sessions#failure'

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  validates :level, inclusion: [1,2,3,4,5]
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :interests
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :interests

  def self.from_omniauth(auth)
    user = where(provider: auth['provider'], uid: auth['uid']).first_or_create

    user.name         = auth.info.name
    user.nickname     = auth.info.nickname
    user.access_token = auth.credentials.token
    user.save!

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

  def ensure_current_user
    unless current_user
      redirect_to signin_path
    end
  end

  def current_user=(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def clear_current_user!
    reset_session
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :ensure_current_user

  def create
    topic = Topic.find(params[:topic_id])

    interest = topic.interests.new(params.require(:interest).permit(:comment, :level))
    interest.user = current_user
    interest.save!

    redirect_to topic
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to root_path
    else
      redirect_to signin_path
    end
  end

  def new
    #this renders new.html.erb
  end

  def destroy
    clear_current_user!
    redirect_to root_path
  end

  def failure
    #this renders failure.html.erb
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :ensure_current_user
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    topic_params = params.require(:topic).permit(:title, :long_description, :focus_area)

    @topic = Topic.new(topic_params)
    we_saved_the_topic_without_error = @topic.save

    if we_saved_the_topic_without_error
      redirect_to @topic, notice: 'Topic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  # def destroy
  #   @topic.destroy
  #   respond_to do |format|
  #     format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :long_description, :focus_area)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/interests/_interest.html.erb
<li><%= interest.comment %> <%= interest.user.name %> </li>
<li><%= interest.level %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IronTopics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navigation_bar' %>
<%= yield %>

</body>
</html>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Iron Topics", root_path, class: "navbar-brand" %>
      <!-- Above is the rails helper way of doing a link, below is the old way -->
      <!-- <a class="navbar-brand" href='<%= root_path %>'>Iron Topics</a> -->
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path, class: "active" %></li>
        <li><%= link_to 'New Topic', new_topic_path %></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user %>
          <%= link_to 'Log Out', signout_path, method: :delete, data: { confirm: "Are you sure?" } %>
          <% else %>
          <%= link_to 'Login with Github', auth_path(provider: 'github') %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/topics/_common_topic_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= simple_form_for(@topic) do |f| %>
    <%= f.input :title %>
    <%= f.input :long_description, class: "long_text_box" %>
    <%= f.input :focus_area%>
    <%= f.button :submit %>
  <% end %>

  <!-- <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :long_description %><br>
    <%= f.text_area :long_description %>
  </div>
  <div class="field">
    <%= f.label :focus_area %><br>
    <%= f.text_field :focus_area %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :long_description %><br>
    <%= f.text_area :long_description %>
  </div>
  <div class="field">
    <%= f.label :focus_area %><br>
    <%= f.text_field :focus_area %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="edit_screen">
<h1>Editing Topic</h1>

<%= render 'common_topic_form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>
</div>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class='topics_heading'>Listing Topics</h1>

<!-- <% @topics.each do |topic| %>
<div class='topic_container'>
  <h2 class='topic_title'><%= link_to topic.title, topic_path(topic) %></h2>
  <p class='topic_desc'><%= topic.long_description %></p>
</div>
<% end %> -->
<div class='row row-centered'>
<% @topics.each do |topic| %>

    <div class='col-xs-6 col-md-3 col-centered topic_container'>
      <h2 class='topic_title_display'><%= link_to topic.title, topic_path(topic) %></h2>
      <p class='topic_desc'><%= topic.long_description %></p>
  </div>

<% end %>
</div>

<br>

app/views/topics/new.html.erb
<div class='new_topics_page'>
<h1>New Topic</h1>

<%= render 'common_topic_form' %>

<%= link_to 'Back', topics_path %>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="interests_page_view">
<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Long description:</strong>
  <%= @topic.long_description %>
</p>

<p>
  <strong>Focus area:</strong>
  <%= @topic.focus_area %>
</p>

<ul>
<%= render @topic.interests %>
</ul>

<!-- <%= form_for([@topic, @topic.interests.new]) do |f| %>
  <ul>
    <li>Comment</li>
    <li><%= f.text_field :comment %></li>
    <li>Level</li>
    <li><%= f.text_field :level %></li>
    <li><%= f.submit %></li>
  </ul>
<% end %> -->

<%= simple_form_for([@topic, @topic.interests.new]) do |f| %>
  <%= f.input :comment %>
  <%= f.input :level %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>
</div>